### ISSUE TITLE
¿ Cómo puedo colaborar ?

### ISSUE THREAD

**Issue by D3Portillo** [midudev/covid-vacuna#1]
Me parece interesante el proyecto y no sé que piensas para que otros países puedan usar esto cómo plantilla o similar que se pueda hacer cualquiera de las siguientes features:

- Usar Airtable u otra DB para consumir los datos con la API (La versión gratuita puede funcionará a la perfección )
- Posibilidad de personalizar la App, temas con Tailwind ? 
- Guía de cómo clonarlo, personalizar, agregar data y montar tu versión en vercel ( Para otros países en la misma situación o personas interesadas, además se puede agregar una convención de nombres en proyectos de vercel cómo sv-vacunacovid.vercel.app , es-vacunacovid.vercel.app , esto pensado para los que no podrán agregar un domain propio )
- Si existe un tutorial , agregarlo cómo recurso de aprendizaje o cómo la propia guía D :

Otra duda/comentarios, me gusta mucho tu contenido y he aprendido mucho de ello, cómo puedo ayudar en este proyecto ?, para "aprender haciendo" y pues aportando a la idea del website.

---

PD: Para trigger del build a Vercel se puede usar un script de Drive y en el evento update de Airtable se gatilla ha drive
lo que luego ejecuta un script a un hook de vercel y generará un build.

**Comment by midudev** [comment]
Hola D3Portillo,

perdona que tardase en contestar, estaba terminando la app! 🧑‍💻 

Pues cualquier cosa siempre es bienvenida. Es verdad que ahora mismo es más bien complicado hacer que se use para otros países.

La verdad es que lo de Tailwind y Airtable no lo pensaba usar para el proyecto, la idea era que fuese lo más sencillo posible para enfocarnos en el valor y que fuese lo más estático posible (de ahí las GH Actions para guardar el json).

Pero cualquier mejora es bienvenida!!!

**Comment by D3Portillo** [comment]
Mil gracias por responder @midudev , me he fijado que hay muchos issues y PR proppuestos, veré si uno me es interesante y le dedicaré un momento a colaborar en aportar código o feedback : )

Saludos!!

**Comment by D3Portillo** [comment]
Si no hay más comentarios que agregar cerraré el issue :tada:
