### ISSUE TITLE
Error previsualización datos del mapa

### ISSUE THREAD

**Issue by Daniellop1** [midudev/covid-vacuna#104]
Hola, al previsualizar los datos del mapa el pop-up sale desplazado.

Estoy usando Safari en Mac OS Big Sur

<img width="1440" alt="Screenshot 2021-01-30 at 22 17 20" src="https://user-images.githubusercontent.com/44546966/106368308-ed99b200-6348-11eb-8805-91c00e4d6ecf.png">

**Comment by sergioedo** [comment]
Creo que es debido a esta otra issue https://github.com/midudev/covid-vacuna/issues/64. Prueba seleccionado el modo por defecto:
<img src="https://user-images.githubusercontent.com/5507031/106640408-4b670d80-6586-11eb-8956-893b73720cc8.png" height="50" width="80">

**Comment by Daniellop1** [comment]
Hola, como ha comentado @sergioedo si que tiene que ver con el selector del tema ya que en modo oscuro este problema no aparece.

Un saludo

**Comment by midudev** [comment]
Esto ha sido arreglado con la migración del dark mode a custom properties.
