### ISSUE TITLE
Calculo erroneo en la población vacunada

### ISSUE THREAD

**Issue by willmontaraces** [midudev/covid-vacuna#107]
![image](https://user-images.githubusercontent.com/49091315/106394370-981edd00-63fc-11eb-860e-69db17ff9c96.png)
Buenas, creo que el calculo actual de la población vacunada es DosisAdministradas/NoHabitantes, cuando deberia de ser (DosisAdministradas-PersonasConPautaCompleta) / NoHabitantes.

**Calculos**
PoblaciónEspaña = 46,94 millones = 46.94 \* 10^6
Población vacunada = DosisAdministradas/NoHabitantes*100 = 1474189 / (46.94 \* 10^6) \* 100 = 3.14%
**Deberia de ser**
Población vacunada = (DosisAdministradas-PersonasConPautaCompleta) / NoHabitantes = (1474189-251866) / (46.94\*10^6) \* 100 = 2.6%

**Comment by midudev** [comment]
Mmmm pero con población vacunada también queremos contar la gente que ha recibido la segunda dosis, no? :O No termino de verlo. Si se llamase "Población vacunada sólo con la primera dosis" tendría sentido pero justamente lo que se busca es saber es la población que se ha vacunado, ya sea con una dosis o las dos.

Luego para eso tenemos otro filtro que sólo habla de la pauta completa.

¿Me estoy perdiendo algo? :D No era el mejor en matemáticas.

**Comment by othermore** [comment]
Cuando se hayan puesto 46.94 millones de dosis en España, a 23.5 millones de personas, cuántas personas habrá vacunadas?

Ahora: 46.94/46.94*100=100%
Lo correcto: 46.94-23.5*100 ~= 50%

Tiene razón willmontaraces

**Comment by midudev** [comment]
Ahora os entiendo. :)

El caso es que yo siempre entendí que por "Dosis Administradas" en realidad se refería a "Primera dosis administrada". Por eso no entendía el cálculo que comentabais 😆 .

Pero claro, si por "Dosis Administrada" se refiere a literalmente a lo que dice, que tiene sentido, entonces lo que comentáis es correcto. 🤗

Me voy a informar a ver y lo cambiaremos. ¡Gracias!

**Comment by willmontaraces** [comment]
Quizás se podría cambiar el nombre a "población con pauta no completa".
Esto resultará importante cuando se apruebe la vacuna de Jonson and Jonson, en la que la pauta completa constituye de una sola dosis.

**Comment by othermore** [comment]
Y estaría bien para dar visibilidad a las dosis necesarias para al menos cubrir las pautas que están a medias, que es algo que va a tener mucha repercusión en las próximas semanas por la falta de stock y los retrasos que está habiendo en la entrega de vacunas

**Comment by midudev** [comment]
Hola @willmontaraces. ¿Puedes revisar el cálculo que hay ahora para ver si es más correcto? ¡Gracias!

**Comment by willmontaraces** [comment]
![image](https://user-images.githubusercontent.com/49091315/106936703-3375c200-671d-11eb-9ef7-a6a1664b83a4.png)
No veo que se haya actualizado el calculo. El valor que esta ahora en población vacunada es el de dosis por cada 100 habitantes. Cuando lógicamente entiendo yo que debería de ser el de personas con una sola dosis.
Quizás el ejemplo se entienda mejor con la siguiente imagen:
![image](https://user-images.githubusercontent.com/49091315/106936884-69b34180-671d-11eb-9dd2-b6c12bb71f1f.png)
Source: https://www.bloomberg.com/graphics/covid-vaccine-tracker-global-distribution/
Lo intentaría actualizar yo, pero desgraciadamente no tengo suficientes conocimientos sobre frontend, quizás si sigue abierto el ticket una semanita mas lo intento

**Comment by othermore** [comment]
Estoy deacuerdo, el cálculo sigue mal

**Comment by midudev** [comment]
:) Prueba ahora a ver qué tal. Me falta arreglar también la tabla, pero poco a poco. ;)

**Comment by othermore** [comment]
Ahora sí está bien arriba :) Yo he estado un rato pegándome para intentar arreglarlo jaja. La cosa es que he visto que los datos vienen directos del json así que habría o que arreglar los json o que recalcular. Y como no controlo mucho de nodejs / frontend, no he sido capaz de arreglarlo yo mismo

**Comment by othermore** [comment]
Acabo de ver el cambio que has hecho, restando los porcentajes. ¿No sería mejor interceptar la lectura del JSON y re-calcular todo bien? Es lo que yo estaba intentando (donde se hace el require del json de los datos) sin éxito.

De esa forma, se podría añadir más fácilmente un campo extra que fuese, por ejemplo, segundas_dosis_pendientes, o similar.

**Comment by midudev** [comment]
Si @othermore, es lo que quiero hacer y haré, pero quería asegurarme que se arregla correctamente antes de replicar este cambio. ;)

**Comment by willmontaraces** [comment]
Por cierto, estoy dejando el ticket abierto hasta que el problema se solucione en el mapa y en la tabla. 
Cuando alguien lo haya implementado y lo vea lo cierro @midudev

**Comment by midudev** [comment]
Ya lo tenemos en la tabla arreglado. Me falta el mapa.

**Comment by frmjar** [comment]
Lo he corregido en el mapa en la PR #157

**Comment by willmontaraces** [comment]
Ya esta live, muchas gracias por vuestro trabajo :)
Cierro la issue.
