### ISSUE TITLE
Sacar porcentaje sobre la gente que se debe vacunar

### ISSUE THREAD

**Issue by jorgemm61** [midudev/covid-vacuna#109]
sacar el porcentaje sobre la gente que se debe vacunar, que entiendo no es el total de la población, ya que creo que los menores no se vacunan.
gran trabajo 

gracias

**Comment by willmontaraces** [comment]
Por ahora no se vacunan, pero probablemente cuando les toque ya estará suficientemente testada para inocularla, al igual que tantas vacunas modernas.
Hasta que el gobierno no publique todos los grupos de vacunación no podremos estar seguros.

**Comment by midudev** [comment]
Gracias @jorgemm61. Por ahora ya tenemos la población de mayores de 18 años en el JSON. Es posible que añadamos un checkbox para cambiar entre ambas poblaciones para justamente poder ver ambos datos.
