### ISSUE TITLE
Añadir fecha de última actualización al JSON

### ISSUE THREAD

**Issue by esmultivac** [midudev/covid-vacuna#113]
Muy buenas,

Como imagino que pilláis los datos de la hoja de cálculo del Ministerio, en ella hay un dato sobre el día de la última actualización de cada una de las autonomías que estaría bien incluir en el JSON, para que quienes queramos consumirlo podamos incluir cuándo se han actualizado los datos por última vez.

Un saludo,

**Comment by frmjar** [comment]
Hola, 
he creado un pull request añadiendo lo que pides.
Échale un ojo y me comentas si prefieres otro formato.
