### ISSUE TITLE
No aparece porcentaje en la barra - Mozilla Firefox

### ISSUE THREAD

**Issue by sanseb19** [midudev/covid-vacuna#115]
No esta apareciendo el porcentaje actual de la barra de progreso:

- No tengo certesa si esto tambien ocurre en safari, pero en mozilla firefox si sucede

![imagen](https://user-images.githubusercontent.com/53236007/106820874-21771f00-664a-11eb-8756-da61312382c2.png)

- Version de Mozilla:
![imagen](https://user-images.githubusercontent.com/53236007/106821333-f3460f00-664a-11eb-9029-5b7992e8474f.png)

**Comment by midudev** [comment]
Gracias por avisar. Me imagino que esto es por los cambios recientes de poner el número en el elemento ::before del `progress`.  ¡Gracias por avisar!

**Comment by frmjar** [comment]
> Gracias por avisar. Me imagino que esto es por los cambios recientes de poner el número en el elemento ::before del `progress`. ¡Gracias por avisar!

He creado una PR solucionando. He explicado por qué se da este problema. Lo copio aquí también.

Resulta que en Firefox y Safari, tanto :before como :after solo se aplican a elementos con contenido.

<element> ::before ***content*** ::after </element>

Sin embargo en elementos tipo 'checkbox' y en nuestro caso el progress no funcionaría el :before.

<input type="checkbox" /> <progress max='100' value={value * 100} data-value=34% />

Por lo visto, Chrome sí que soporta estos pseudo-elementos en elementos sin contenido. Por eso funciona en Crome y no en Firefox o Safari.
