### ISSUE TITLE
Población vacunada

### ISSUE THREAD

**Issue by mariaega11** [midudev/covid-vacuna#119]
Buenas, 
El % donde mencionais, población vacunada, me consta que es incorrecto, razón:
En estos momentos la situación es la siguiente según vuestra web:
Dosis administradas: 1.865.342 
Población vacunada: 3,97%
Personas con dosis completa:586.122 (1,25% de la población)

Con estos datos, las personas que han recibido 1dosis son,  1.865.342-(586.122 x 2) =693.098 
Personas q han recibido 2 dosis 586.122
Total personas vacunadas 693.098+586.122=1.279.220
Lo que supone el 2,73%de la Población y no el 3,97%.

 Si creéis que 1865342 personas se han vacunado, ESTAIS EQUIVOCADOS,  no es lo mismo dosis administradas que personas vacunadas
Gracias de antemano.

**Comment by midudev** [comment]
😆 Vale que ESTAMOS EQUIVOCADOS. Lo REVISAREMOS jajajaja ¡Gracias por la explicación!

**Comment by mariaega11** [comment]
Jajajaja veo que habéis captado el mensaje (perdón por las mayúsculas del
mail anterior) 😁

**Comment by midudev** [comment]
Ya debería estar arreglado el cálculo.

**Comment by mariaega11** [comment]
Si, lo he visto. Muchas gracias!

**Comment by mariaega11** [comment]
Buenas tardes de nuevo,
Primero enhorabuena por el nuevo gráfico donde se muestra la población
vacunada por edades en España. Es muy práctica.
No obstante encuentro un error:
La población INE que marcais es errónea. Ponéis en todos los rangos el
doble de lo  que realmente hay. Desgraciadamente no somos 33 millones de
personas entre 25-49 años, si no 16,7 millones.

Igualmente os felicito por la gráfica.
la próxima vez que os arregle algo os cobraré que ya llevo dos ,😋

**Comment by mariaega11** [comment]
Buenas de nuevo, ya he visto que habéis arreglado el problema del email
anterior.

Ya para dejarlo totalmente perfecto,
En la etiqueta emergente que sale al cliquear en las gráficas, donde
ponéis " se ha puesto una dosis a.... " Deberíais poner " se ha puesto al
menos una dosis a...." Ese dato es la suma de las personas que se han
puesto una dosis y las que se han puesto dos.
Espero que no os moleste tanto reTOCque, solo es por ayudar. ;)
