### ISSUE TITLE
Consulta sobre variable representada en el mapa

### ISSUE THREAD

**Issue by sigdeletras** [midudev/covid-vacuna#123]
Saludos!

¿Qué dato se está usando concretamente para "colorear" el mapa?

En SpainMap.jsx se indica que es el porcentaje ¿pero a qué porcentaje se refiere? ¿entregadas, poblaciónAdministrada o poblacionCompletas?

Creo que se le puede sacar más jugo a ese mapa temático (técnicamente se denomina un mapa de coropletas), por ejemlo añadiendo un subtítulo de la variable representada, pero no logro saber qué representa concretamente. 

A todos esto mis más sinceras felicitaciones a @midudev y todos los que estáis colaborando.

**Comment by sigdeletras** [comment]
Vale....me respondo yo mismo. Actualmente se representa el porcentajeEntregadas

**Comment by midudev** [comment]
La cierro ya que te has autocontestado. Me miraré el tema de los colores que a mi tampoco me termina de convencer. :)
