### ISSUE TITLE
El % que indican es erróneo 

### ISSUE THREAD

**Issue by Ead53** [midudev/covid-vacuna#129]
El % de población que indican que está vacunado no coincide del primer cuadro con el listado por autonomías, el primero es erróneo, el correcto es el 4,62 que aparece en el listado por autonomías, el 2,83% del primer recuadro esta mal.
Saludos
Eusebio

**Comment by midudev** [comment]
El cálculo correcto es el de 2,83%. Las dosis administradas cuentan las dos dosis que ha podido recibir una persona.

4,62% serían las dosis administradas por número de habitantes y 2,83% la población vacunada (alguna de la cuál ha recibido dos dosis).

**Comment by Ead53** [comment]
Gracias por contestar, pero no estamos de acuerdo.
en los cuadros superiores, se ve dosis distribuidas y dosis administradas y
pauta completa.
La dosis administradas, es decir ya inoculadas en las personas, será la
población que ha recibido la primera dosis, es decir será igual a
"población vacunada", si quieres añadir con primera dosis (aunque alguna
vacuna será de una sola dosis), pero para eso está la opción de seleccionar
población con pauta completa que da 1,90%, de otro modo población vacunada
que es?, ni es la pauta completa, ni es el total que han recibido la
primera dosis, entonces ese 2,86% que es?, dices "dosis que ha podido
recibir una persona" , no entiendo eso la población vacunada tendrá que ser
2233249/47000000 (o la cifra exacta que uséis para el cálculo) eso da los
4,62% aprox.
Disculpa, si estoy en un error, es solo con ánimo de precisar el dato, pero
ese dato no le encuentro lógica ni modo de calcularlo.
Saludos
Eusebio

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by midudev** [comment]
**La población vacunada** es la población que ha podido recibir una o más vacunas.
**Las dosis administradas** es el número de dosis que se han administrado, independientemente si dos dosis las ha recibido la misma persona.

Por eso **ahora mismo** la fórmula sería:
Dosis administradas - Personas con pauta completa = Población vacunada = Número de persona con una o más vacunas

En números del último día:
(2233249-889683)/46940000 = 0,028

De esta forma evitamos contar dos veces personas que tienen dos dosis administradas.

Como bien dices, **más adelante el cálculo será más complejo** porque habrá vacunas que sólo serán de una dosis. Lo podremos calcular porque tendremos la posibilidad de saber cuántas vacunas del tipo monodosis se han inoculado.

**Comment by Ead53** [comment]
Gracias de nuevo por contestar, eres muy amable.

No obstante, aunque ahora veo como sacas el % de personas vacunadas, (el
dato que sale de esa resta no sale por ningún sitio, ni se indica que se
debe restar una cantidad de otra que sale en los cuadros....),pero siento
seguir sin estar de acuerdo contigo, ya que si vamos al texto literal
POBLACION VACUNADA, ahí se deben incluir todos, ya dice la palabra,
"población vacunada", otra cosa sería si dijes POBLACION CON UNA SOLA
VACUNA, porque viéndolo al revés, si solo nos fijamos al %, que es lo que
se ve y lo multiplicáramos por la población, no saldrían que POBLACIÓN
VACUNADA es 2,86x46.940.000=1.314.320 personas, lo que no es cierto, habría
en ese caso que indicar CON UNA SOLA DOSIS, pero sigo diciendo que la
población que ha sido vacunada (aunque solo sea una vez, pero si ha sido
vacunada al fin y al cabo), es del 4,76%, por cierto, veo que ahora habéis
cambiado el % del cuadro por autonomías, ahora por lo menos es el mismo,
aunque lamentablemente ahora están los dos mal, según mi criterio claro....

También podía quedar más claro de otra forma, en cada uno de los dos
cuadros superiores, añadir el % de cada cantidad, así en dosis
administradas saldría 4,76% y en pauta completa 1,90, pero o cambias el
título del cuadro inferior o sigo estando en desacuerdo, lo correcto sería
POBLACION CON 1 VACUNA y POBLACIÓN CON PAUTA COMPLETA, pero si pones
POBLACIÓN VACUNADA, no es cierto, la población vacunada no es el 2,86, ese
% es de los que han recibido UNA VACUNA y hay que añadir los que han
recibido las dos.

Bueno, no quiero cansarte, es una discusión tonta, pero siempre me ha
gustado la precisión en las estadísticas y matemáticas, de hecho ha sido mi
profesión y en mi carrera se estudia estadística y muchas veces son
diferentes planteamientos, más que errores, pero para mi ya te digo,
cualquiera a quien le preguntes o le digas el 2,86% de la población está
vacunada, le darás una información INCOMPLETA, porque tendrías MÁS EL 1,90
que tiene la dos vacunas.... o no?, te invito a que hagas la
prueba....jejeje,

Bueno, repito, disculpa si te hago perder tiempo, pero hasta que no me
convenzo de las cosas, no paro, lo siento.
Saludos
Eusebio

**Comment by midudev** [comment]
Gracias a ti por el tiempo. Al final lo que intentamos es mejorar los datos.

Puedo entender lo que comentas que al final es un tema semántico pero si lees "Población vacunada" como "Población que al menos ha recibido una vacuna" verás que tiene sentido.

Dosis administradas 4,76%
Población vacunada con al menos una dosis 2,86%
Población vacunada con pauta completa 1,90%

Le daré una vuelta para cambiar el texto para que quede todavía más claro. :)

Saludos.
