### ISSUE TITLE
% población vacunado no refresca datos

### ISSUE THREAD

**Issue by xyulex** [midudev/covid-vacuna#132]
Si miráis los datos totales, hoy 10/02 pone que % población vacunada es del 4.63 (en la tabla de autonomías) mientras que en los radiobuttons de arriba marca 2,89%.

**Comment by frmjar** [comment]
Duplicado de #129 y de #127 

Por lo que he visto el "error" está aquí.

```js
const CALCULATIONS = {
  [FILTERS.parcial]: totals =>
    totals.porcentajePoblacionAdministradas - totals.porcentajePoblacionCompletas,
  [FILTERS.completa]: totals =>
    totals.porcentajePoblacionCompletas
}
```

Esto se introdujo hace 5 días por @midudev en el commit [50263593e9471ccc0c280feb48d3417f187ccf13](https://github.com/midudev/covid-vacuna/commit/50263593e9471ccc0c280feb48d3417f187ccf13)

Si no recuerdo mal, esto se introdujo porque había algunos usuarios que defendían que esta tenía que ser la forma correcta de calcular este dato. Pero si es cierto que difiera demasiado de los datos oficiales.

Habría que hacer un consenso de cómo calcularlos correctamente.

**Comment by midudev** [comment]
Ahora ya salen los mismos datos en las tablas y el progreso de arriba.
