### ISSUE TITLE
404: Descargar datos en formato JSON 

### ISSUE THREAD

**Issue by sanchis** [midudev/covid-vacuna#141]
Hola buenas, he detectado un pequeño problema a la hora de descargar los datos desde la aplicación si no hay filtro establecido.

Para reproducirlo sigue los pasos.
- Entra en la web.
- Click en descargar datos.

Esto solo pasa si no hay ninguna fecha seleccionada. 

![Screenshot_25](https://user-images.githubusercontent.com/12100597/107861800-87348980-6e48-11eb-832c-820e91968a3b.png)

**Comment by midudev** [comment]
¡Hola! Gracias por avisar. En lugar de ocultar el link, lo he arreglado en este commit: https://github.com/midudev/covid-vacuna/commit/e1ffca29374ae5afbffa735fceb09f9c5443532e

¡Saludos!
Miguel
