### ISSUE TITLE
Propuesta

### ISSUE THREAD

**Issue by FramesSanz** [midudev/covid-vacuna#144]
Hola, felicidades a todos y todas por el trabajo, consulto la página casi todos los días.

Mi sugerencia es que implementéis un apartado de comentarios, a través de ellos tendríais algún feedback de usuario y os sería más fácil depurar alguna funcionalidad además de hacer la app algo más atractiva para el usuario.

Un saludo

**Comment by midudev** [comment]
Hola @FramesSanz. ¡Gracias por la propuesta! Lo cierto es que vamos a intentar mantener el sistema de issues de GitHub para recibir este tiempo de propuestas. También me llegan muchas ideas por Twitter que al final también las hemos implementado. :) Abrir más canales me generaría más ruido y tampoco tengo mucho tiempo para dedicarle, por desgracia. 😆
