### ISSUE TITLE
Gráfica de progreso

### ISSUE THREAD

**Issue by cenguidanos** [midudev/covid-vacuna#15]
Hi devs,

He pensado en utilizar [recharts](https://github.com/recharts/recharts) para la gráfica. ¿Qué os parece? Creo que es de las librerías menos pesadas y con buen resultado, fácil de implementar y mantener.

* [Recharts](https://bundlephobia.com/result?p=recharts@2.0.3): 120.5kb minified + gzipped
* [Chart.js](https://bundlephobia.com/result?p=chart.js@2.9.4): 123.8kb minified + gzipped
* [Echarts](https://bundlephobia.com/result?p=echarts@5.0.1): 304.9kb minified + gzipped

Salud!

**Comment by midudev** [comment]
Totalmente de acuerdo. :) Recharts me encanta, la verdad. Lo mejor, si pudiéramos, es que se cargase sólo cuando entra en el viewport (si seguimos haciendo todo una sola página).

**Comment by cenguidanos** [comment]
Perfect

**Comment by cenguidanos** [comment]
¿Qué idea tienes de las gráficas? Tengo la gráfica estilizada y con el IntersectionObserver. Es reutilizable y muestra las **dosisAdministradasTotales** y las **dosisEntregadasTotales** pero hay muchas formas de hacerlo y enfocarlo... te hago un pull y em dius!

**Comment by midudev** [comment]
Ha quedao finisimo!!!! 🚀  Lo que tengo que mirar por qué las dosis distribuidas no hay datos al principio, igual cambiaron el campo que usaban en el gobierno. :D

**Comment by cenguidanos** [comment]
Gracias tío. Sí, no sabía muy bien a qué se debía pero algo así será xd

**Comment by midudev** [comment]
Efectivamente era eso. Ya está arreglado. 👍
