### ISSUE TITLE
Mapa de comunidades autónomas: Porcentaje es suma incorrecta

### ISSUE THREAD

**Issue by javpasto** [midudev/covid-vacuna#151]
En el mapa interactivo, el porcentaje de población vacunada en cada comunidad autónoma es la suma de la población totalmente vacunada y la de la población con una sola dosis.

**Comment by NicoMoli** [comment]
Hola a todos! En este bug, la informacion correcta a mostrar seria el PorcentajePoblacionAdministradas?

Gracias!

**Comment by oespino** [comment]
Esta issue se solucionó en la PR #157

**Comment by FredDlt** [comment]
Serian tan amables de cerrar la issue si ya se soluciono 😊

> Esta issue se solucionó en la PR #157
