### ISSUE TITLE
Implementar Typescript

### ISSUE THREAD

**Issue by cenguidanos** [midudev/covid-vacuna#16]
Hi @midudev,

¿Alguna razón para no utilizar Typescript?

**Comment by cenguidanos** [comment]
Te he dejado una pull request con el cambio a Typescript igualmente

**Comment by midudev** [comment]
Hola crack. ¡Muchas gracias por el currazo!

Por ahora, prefiero que no pasemos el proyecto a TypeScript. Me parece que tiene usos interesantes pero en este proyecto tampoco le veo las ventajas que tiene respecto al coste que me comportaría de mantenimiento, build y que más gente se anime a participar.
