### ISSUE TITLE
Estimaciones de población vacunada demasiado pesimistas.

### ISSUE THREAD

**Issue by santialbo** [midudev/covid-vacuna#161]
Ahora mismo las estimaciones se están calculando en base a todo el proceso de vacunación. Este es un planteamiento pesimista porque no está teniendo en cuenta que el volumen de entrega de vacunas está creciendo.

Haciendo un cálculo rápido con las entregas de la última semana (~1,1M) vemos que se vacunaría a toda la población en alrededor de un año y medio, mucho menos del dato que se está presentando (30-6-2023 a día de esta PR).

En el esquema siguiente, la opción A viene a explicar lo que se está haciendo ahora mismo. Propongo que se utilice una de las otras dos opciones:
- Opción B: Asumir que el volumen de entregas se va a mantener constante y utilizar solo los datos de crecimiento de la última semana. Es la opción más conservadora.
- Opción C: Hacer una regresión polinomial con los datos. Probablemente sea la que acabe acertando más.

![Untitled-2021-03-13-1821](https://user-images.githubusercontent.com/1557563/111038487-8718b100-8429-11eb-954b-27826dac21ed.png)

**Comment by carlosjdelgado** [comment]
Yo lo haría usando la media de dosis administradas en la ultima semana y teniendo en cuenta las ya administradas, pero no tendría en cuenta las que se van a recibir ni las recibidas porque aunque esta claro que tendrá impacto a futuro no representa una estimación real basada en datos del presente, no se si me explico.

Lo que si creo es que la formula del calculo tendría que cambiar para tomar como referencia las pautas completas de vacunación en lugar de las dosis individuales, porque ahora mismo se esta estimando en base a doble dosis y cuando llegue la vacuna de jannsen será necesaria solo una dosis y se descuadraría la estimación.

**Comment by Johnbo** [comment]
En el issue #174 también lo estamos discutiendo y creo que lleváis toda la razón.
