### ISSUE TITLE
ERROR carga de datos desde la web de sanidad

### ISSUE THREAD

**Issue by pablis6** [midudev/covid-vacuna#162]
Buenas,
he detectado que los datos publicados por el gobierno el viernes 12 de marzo no se cargaron en la web.
El script está intentando acceder a los datos con la misma URL que siempre: 
`https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov/documentos/Informe_Comunicacion_20210312.ods`
pero por algún motivo esta URL ha cambiado y ese día los datos se publicaron en la siguiente web:
`https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov/documentos/Informe_GIV_comunicacion_20210312.ods`
Habrá que ver si finalmente se mantiene el nuevo formato o ha sido un error en el nombre del archivo en un día puntual.
En cualquier caso, creo que habría que meter a mano los datos del día 12 para tener el histórico completo.

Saludos.

**Comment by midudev** [comment]
¡Gracias por el aviso!

**Comment by midudev** [comment]
He subido el reporte manualmente. Parece que, por suerte, solo ha sido algo puntual. :)
