### ISSUE TITLE
Desde el día 17 no se actualizan los datos

### ISSUE THREAD

**Issue by Natitis** [midudev/covid-vacuna#166]
Simplente eso, no hay datos actualizados desde el día 17, saludos!

**Comment by devagja** [comment]
Buenas,
 se debe a que por parte del Estado han dejado de generar la información que se consumía en la web,
desconozco si es por un error que tienen que solucionar o porque oficialmente el Estado ha dejado de dar soporte,

relaciono esta incidencia con la mía, dado que es la misma incidencia 
https://github.com/midudev/covid-vacuna/issues/165

**Comment by drobledom** [comment]
Lo que no entiendo es por qué refleja el último día como día 17 cuando el último dato disponible es del 18:

[https://github.com/midudev/covid-vacuna/blob/main/public/data/20210318.json](https://github.com/midudev/covid-vacuna/blob/main/public/data/20210318.json)

Efectivamente el estado no ha hecho público ningún dato desde entonces. Esperemos que sea por el puente y hoy retomen.

**Comment by pablis6** [comment]
He visto que se han publicado ya los datos de hoy y se han descargado, pero por algún motivo no los carga, igual que el jueves.
Curiosamente en el selector hay 50 datos, no se si tendrá algo que ver o no, pero por si ayuda...
Es raro lo que está pasando

**Comment by devagja** [comment]
Correcto, esto se debe al despliegue automatizado por Vercel de la web en producción continua fallando, es cuestión de revisar el origen del fallo en la compilación

https://github.com/midudev/covid-vacuna/deployments/activity_log?environment=Production

**Comment by midudev** [comment]
Ya está arreglado todo.

El día 19 fue festivo y por eso no hay datos.
He arreglado el pase a producción de Vercel. :)
