### ISSUE TITLE
Tratamiento de datos con información sobre la vacunación en las fuerzas armadas

### ISSUE THREAD

**Issue by carlosjdelgado** [midudev/covid-vacuna#169]
Recientemente el ministerio ha incluido la información sobre la vacunación en la población militar y abro este issue para que debatamos como debería tratarse esta información:

- Opción 1: Eliminar la información de la página y que solo refleje datos acerca de la población civil como hasta ahora.
- Opción 2: Tener en cuenta la información y arreglar la tabla para que se refleje esta información correctamente, añadiendo el total de la población militar para poder calcular el porcentaje de vacunados y arreglando la ordenación de las columnas.

En mi opinión personal no esta de mas reflejar esta información que podría serle a alguien de utilidad, pero quiero saber vuestras opiniones antes de hacer nada con esto. 

@midudev tu que opinas?

**Comment by esqui2002** [comment]
Yo creo que lo correcto seria la opción 2, puesto que si se eliminan esos datos, el porcentaje no seria real.

**Comment by drobledom** [comment]
Hola,

Alguna manera de saber la población total de las Fuerzas Armadas? No parece que esté en ningún lugar público
