### ISSUE TITLE
Date format is wrong.

### ISSUE THREAD

**Issue by hojo24** [midudev/covid-vacuna#172]
Dear development team,

the date format is wrong. It is set in English notation. It should be dd/mm/yyyy.
That's why the sorting in your date listing goes wrong.

Kind regards,

John Nellen

**Comment by drobledom** [comment]
Where? I see the date as dd/mm/yyyy (Maybe it was fixed in a previous commit)

![image](https://user-images.githubusercontent.com/15011687/116013693-ceea4500-a631-11eb-8a21-d441985e9d13.png)
