### ISSUE TITLE
Estimación Población Vacunada

### ISSUE THREAD

**Issue by lmendiola555** [midudev/covid-vacuna#174]
Hola, como no se especifica, supongo que la Estimación de Población Vacunada está calculada con el ritmo medio de vacunación de todo el periodo en el que se ha vacunado. Creo que sería bueno ver también la estimación con respecto al ritmo de vacunación de la última semana o últimos siete días.
Creo que daría una visión mas realista, aún conservando la estimación actual y especificando como está calculada cada una.

Gracias y saludos. Estáis haciendo un excelente trabajo.

**Comment by Johnbo** [comment]
Venía a añadir un issue diciendo justamente lo mismo. No es realista hacer una proyección a futuro con un promedio de lo que se ha inoculado desde el 28 de diciembre hasta ahora, y precisamente son esos números los que dan alas a los agoreros. 

Si no modificar el cálculo, al menos se debería informar de cómo está hecho el actual y por qué no es realista.

**Comment by hithwen** [comment]
Si estaría bien saber si la proyección es lineal, una interpolación o qué

**Comment by Johnbo** [comment]
Mirando el repositorio, parece que cada cierto tiempo cambia la constante START_DATA_VACCINATION* para la estimación de población vacunada y que actualmente está tomando el ritmo de todo el mes de abril como patrón para la estimación. Me extraña, porque se aleja mucho de la estimación que Miguel Ángel Reinoso hace con datos de la última semana, por los cuales llegaríamos al 70% de población vacunada en julio: https://twitter.com/mianrey/status/1386442323110678528

* Suponiendo que esté en formato d/m/a y no m/d/a, ya que tiene el valor 01/04/2021
