### ISSUE TITLE
añadir grafico con proyecciones

### ISSUE THREAD

**Issue by hithwen** [midudev/covid-vacuna#178]
Primero gracias por la web, es super util :)
Teneis un por un lado la proyección en fechas de cuando va a estar vacunada el 50%, 75% y 100% de la población y por otro el gráfico temporal de vacunas administradas y recibidas.

Me gustaría que se añadiese un gráfico que mostrase ambas cosas. Sería como una ampliación del que ya hay pero mostrando el futuro y no sólo el pasado, con una linea o cambio de color que muestre qué parte es la real y que parte la proyectada y algún tipo de indicador en las fechas de los hitos 50, 75 y 100

**Comment by Johnbo** [comment]
Lo que dices podría ayudar a entender lo expuesto en las issues #174 y #161, pero antes de nada creo que sería más sensato corregir la regla de cálculo.
