### ISSUE TITLE
Propuesta de cambio de gráficos

### ISSUE THREAD

**Issue by BAC93** [midudev/covid-vacuna#181]
Me encanta lo que habéis hecho, lo sigo a diario.

Desde el desconocimiento de programación, sugiero cambiar el tipo de gráfico del apartado "Población vacunada por edades / grupos de edad en España".

Creo que sería más ilustrativo si hubiera un Pie Chart (gráfico de quesito) para cada grupo de edad con las tres secciones en cada uno de ellos (1. Sin vacunar, 2. Con pauta incompleta, 3. Con pauta completa).

Muchas gracias por vuestro trabajo! :)

**Comment by drobledom** [comment]
La librería recharts que está metida en el proyecto incluye pie charts así que tampoco había mucho problema. Lo podría cambiar si se quiere. Qué opinas @midudev ?

Lo único es que:
- En mi opinión hay demasiados grupos de edades como para mostrar todos los gráficos del tirón (demasiado gráfico en pantalla), quizás sería mejor que solo se mostrara uno junto con un selector de grupo a mostrar (o round form con todos, no sé)
- No se podría mostrar la información de total población, vacunados 1 dosis y vacunados pauta completa como ahora porque no tendría sentido el gráfico. Debería cambiarse por: población pendiente de vacunar, población con una dosis (o pauta incompleta) y población completamente vacunada

**Comment by BAC93** [comment]
Hola. Gracias por tu respuesta.

- A tu primera observación: me parece genial lo que propones del selector para cada grupo de edad (y mostrar entonces un sólo gráfico según la selección).

- A tu segunda observación: efectivamente, como digo, creo que deberían ser esas tres categorías (
1. Sin vacunar, 2. Con pauta incompleta, 3. Con pauta completa).

Muchas gracias por vuestro tiempo!
