### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by fjrodriguezl** [midudev/covid-vacuna#185]
Buenos días, lo primero dar la enhorabuena por todo el trabajo estupenda página.

Os envío una sugerencia, se podría desarrollar un filtro para el gráfico de Población vacunada por edades en España por CCAA, así se podría ver las franjas de edad por CCAA.

Muchas gracias

**Comment by drobledom** [comment]
Hola,

La tabla de comunidades es interactiva y si pinchas en alguna comunidad te hace filtro a dicha comunidad y la mayoría de bloques (el de edades incluido) cambian los datos a en concreto los de esa comunidad.

![image](https://user-images.githubusercontent.com/15011687/116399796-98771a80-a829-11eb-97fb-a613949ca271.png)

**Comment by oespino** [comment]
Creo que una buena mejora sería que se filtrara también al pulsar en el mapa, como ya ocurre al hacerlo en la tabla
