### ISSUE TITLE
Propuesta

### ISSUE THREAD

**Issue by XxJoseLxX** [midudev/covid-vacuna#187]
Hola, muchas gracias de nuevo por la app;

quería proponer un cambio (en la versión de móvil) en la barra de evolución del porcentaje de vacunados. Creo que en vez de dos barras: vacunados/pauta completa, se podría unificar la información en una sola, algo similar al gráfico de dosis distribuidas, que contenga ambas informaciones con distinto color en la misma barra, igual un azul oscuro para la pauta completa y uno claro para una sola dosis, por ej.

También quería decir que al mantener el dedo arrastrado sobre el nuevo gráfico de vacunas por edades de población se vuelve loca la pantalla al llegar al extremo derecho, porque se vuelve más pequeño el gráfico al interactuar en él y debería estar al mismo tamaño en la página independientemente de que se seleccione o no. Un saludo.

**Comment by oespino** [comment]
Hola,

tengo en local una parte hecha para no usar el elemento progress y usar span con ancho calculado uno al lado del otro. El problema que me encuentro principalmente es donde escribir los porcentajes de cada uno.

![image](https://user-images.githubusercontent.com/37581410/117568569-49e73d00-b0c1-11eb-94a2-22d6b820c6ca.png)

![image](https://user-images.githubusercontent.com/37581410/117568635-a77b8980-b0c1-11eb-8548-1b83bf26871c.png)

No queda muy bien esta opción en móvil. Si alguien tiene una propuesta lo puedo intentar arreglar.
