### ISSUE TITLE
Estimación

### ISSUE THREAD

**Issue by plasavall** [midudev/covid-vacuna#190]
Buenos días:

Supongo que hacéis la estimación de la pobalción vacunada de 50, 75 y 100% con una predicción lineal, ya que va actualizando y acercándose más según sube o se mantiene el alto ritmo de los útlimos días. No obstante, dada la evoluciión de los datos quizá sería interesante añadir también una predicción con una sigmoide, por ejemplo, que tiene más pinta de ir a ser la forma final de la curva.

¿Hay algún impedimento para esto o una complicación que yo no esté viendo ahora mismo por estar fuera del problema?

Espero que no moleste este comentario, me encanta vuestra página y creo que hacéis un gran trabajo.

Saludos!

**Comment by felixortegam** [comment]
![imagen](https://user-images.githubusercontent.com/4701534/125994836-84593387-49e3-42a3-8d5c-b87b6a39cb6e.png)

Gracias lo primero por vuestro trabajo, he buscado el último issue donde poder poner esta captura ya que está relacionada.

Como veis, la fecha de estimación se ha adelantado a la real.

Saludos!

**Comment by Johnbo** [comment]
En este momento, con un 51,22% de población vacunada con pauta completa, la estimación del 50% dice que se completará mañana.
