### ISSUE TITLE
barra separada para el grupo de 40-49

### ISSUE THREAD

**Issue by hithwen** [midudev/covid-vacuna#192]
El siguiente grupo a vacunar será: Personas entre 40 y 49 años.

https://www.vacunacovid.gob.es/preguntas-y-respuestas/cuando-me-vacuno

asi que creo que deberian tener su barra aparte

**Comment by drobledom** [comment]
Los datos se extraen directamente del informe oficial del ministerio que da los datos agrupados  en el rango de edad 25-49. Por tanto,  es imposible desagregar esta información (a no ser que el ministerio empiece a hacerlo)

**Comment by midudev** [comment]
Como dice @drobledom, actualmente no podemos separar los datos porque no los disponemos. Pero gracias por la idea. :)
