### ISSUE TITLE
Ampliar datos de la web para dar más info de COVID y de vacunas

### ISSUE THREAD

**Issue by SergioGordillo** [midudev/covid-vacuna#197]
Buenas,

Quizás suene ambiciosa, pero tengo una propuesta que si se pudiera llevar a cabo creo que aportaría mucho valor a la web. Creo que se podrían facilitar:

· Datos sobre casos confirmados, hospitalización, UCI y muertes por rango de edad en España por COVID.
· Datos sobre situación de cada variante de forma gráfica y mediante un hover sobre el gráfico informar de las características de cada variante (mayor transmisibilidad, mayor virulencia etc.).
· Datos sobre la eficacia de cada vacuna tras primera y segunda dosis.
· Estimación de vidas salvadas por las vacunas en España.
· Datos sobre % de efectos secundarios presuntamente ligados a cada vacuna en España, y a ser posible, si se está facilitando esa información que lo desconozco, % por tramos de edad de la gravedad de dichos efectos secundarios (leves, hospitalización, UCI, muerte).
· Datos sobre % de población afectada de long COVID por rangos de edad.

Muchas gracias, saludos.

**Comment by midudev** [comment]
Se sale del scope del proyecto, que quería que fuese muy focalizado en la vacunación. Pero gracias por la idea, crack! 🤗
