### ISSUE TITLE
Permitir escribir parcialmente la comunidad para filtrar la tabla

### ISSUE THREAD

**Issue by dann41** [midudev/covid-vacuna#20]
Estaría genial poder filtrar por comunidad con un autocomplete.

Si no, quizás marcar de otro color la fila seleccionada para facilitar la lectura de la fila entera.

**Comment by pablis6** [comment]
También puede ser en lugar de click, el hover de la línea entera...

**Comment by midudev** [comment]
Ya se hizo que se pudiera marcar la línea al hacer hover y además se puede hacer click en ella para cambiar los datos. :)
