### ISSUE TITLE
Sitio sin actualizar / problemas de certificados

### ISSUE THREAD

**Issue by hithwen** [midudev/covid-vacuna#208]
El sitio lleva unos días sin actualizarse, aunq veo q el commit diario se está realizando
![image](https://user-images.githubusercontent.com/611228/123270847-8e5b5a80-d500-11eb-935d-e940d8ebc763.png)

Si hago un force reload (en chrome) me sale este error:
![image](https://user-images.githubusercontent.com/611228/123270986-aaf79280-d500-11eb-84fd-fc42b1b9b4a2.png)

En safari:
![image](https://user-images.githubusercontent.com/611228/123271060-bc409f00-d500-11eb-82e1-1626bacf3521.png)

**Comment by oespino** [comment]
Hola, estás accediendo a través de algún proxy?

**Comment by midudev** [comment]
He intentado replicar el error en diferentes dispositivos y no he encontrado nada raro.

**Comment by hithwen** [comment]
No, no estaba accediendo desde un proxy pero parece que ya funciona
