### ISSUE TITLE
No se ve algunos textos

### ISSUE THREAD

**Issue by pangeasi** [midudev/covid-vacuna#26]
![Captura de pantalla de 2021-01-22 19-32-41](https://user-images.githubusercontent.com/28918459/105530931-daec0100-5ce8-11eb-9f82-ba0e79d32f75.png)

En tema claro funciona bien, pero en dark y el otro parece que hay alguna propiedad filter que hace que no se vea.

**Comment by midudev** [comment]
¿Qué navegador y sistema operativo usas?

**Comment by pangeasi** [comment]
firefox y ubuntu, este es mi user-agent
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0

**Comment by midudev** [comment]
Creo que quitando la animación esto debería estar arreglado. ¿Le puedes echar un vistazo? :)

**Comment by soker90** [comment]
@midudev parece que sigue sin verse bien en Firefox :'(

**Comment by midudev** [comment]
@soker90 prueba otra vez ahora... 😆

**Comment by soker90** [comment]
@midudev ahora si!! que gustazo xD
