### ISSUE TITLE
Versión UK

### ISSUE THREAD

**Issue by pabrodez** [midudev/covid-vacuna#42]
He hecho una versión para UK, que es un fork, pero manteniéndolo simple. https://covid-vaccine.app/

Como, sinceramente, soy un novato, no sé qué está bien o mal. Además, no estoy seguro de si la atribución que he descrito es apropiada.

Solo me falta meter una GitHub action para descargar a diario el set de datos. Afortunadamente, la web de UK publica en formato JSON.

Los datos de la vacunación en UK son muy interesantes porque se pueden desgranar a nivel hospital, y hasta barrios. Desafortunadamente, este nivel de detalle viene con un precio: es semanal. Es decir, el acumulado de vacunaciones diario solo muestra los totales de primera y segunda dosis.

Gracias.

**Comment by midudev** [comment]
¡Qué genial! Lo he añadido al README. Miraré a ver si en la propia página también añado una serie de links por si más gente se anima a hacer forks para otros países. ¡Gracias crack!
