### ISSUE TITLE
Unificar graficas

### ISSUE THREAD

**Issue by piranna** [midudev/covid-vacuna#43]
Usar una unica grafica para mostrar el numero de dosis entregadas (¿quizas apiladas las de distintos fabricantes?) y el numero de dosis administradas, asi si ve mejor la relacion entre ambas.

**Comment by pangeasi** [comment]
Me parece fantástica esta idea, también podrían mostrarse a modo de pestañas por ejemplo.

**Comment by piranna** [comment]
En una sola grafica es mejor, asi se comparan directamente. Ademas las unidades son las mismas, no hay que hacer nada, el mapeo de los datos es directo :-)

**Comment by sergioedo** [comment]
Incluso para la barra de progreso de vacunados, sería útil ver a la vez %1a dosis vs pauta completa (y evitar el radio button, siempre que entro a mirar chequeo los dos valores, si se vieran los dos de primeras). Puede que doble barra de progreso, o una sobre las otra.

**Comment by othermore** [comment]
+1 ... Comparar entre dosis puestas y pautas completas te deja ver las primeras dosis que se han puesto cada semana.

Estaría bien también mostrar cuántas primeras dosis hay ahora.mismo con las de 21 días de antigüedad, y cuántas va a haber en las próximas semanas, para hacer una proyección del número de dosis necesarias para poner la segunda dosis en 21 dias
