### ISSUE TITLE
Añadir mapas vacunación

### ISSUE THREAD

**Issue by hugojm** [midudev/covid-vacuna#47]
Hola, 
Me gustaría contribuir mediante la creación de mapas interactivos como el siguiente:

https://vega.github.io/editor/#/gist/b78cf5fbcc610fdee369c4be11f2c64a/spec.json

**Comment by midudev** [comment]
Me parece genial Hugo. ¡Dale caña! Pero a ver si puedes añadir las Canarias, que mis colegas de allí se me enfadan cuando no los pongo en los mapas jajaja :)

**Comment by jahermosilla** [comment]
Hola,
He creado un dataset que incluye Península Ibérica, Baleares y Canarias en formato GeoJSON.
[ccaa.zip](https://github.com/midudev/covid-vacuna/files/5862313/ccaa.zip)

**Comment by hugojm** [comment]
Tengo algunos gráficos generados y en formato html pero no consigo implementarlos en index.js

**Comment by cenguidanos** [comment]
Creo que esto puede ayudarte:

* [GeoJSON](https://github.com/codeforamerica/click_that_hood/blob/master/public/data/spain-provinces.geojson)
* [Mapbox](https://docs.mapbox.com/)

**Comment by nacholopex** [comment]
Hay pendiente de merge una pull request https://github.com/midudev/covid-vacuna/pull/65 con esto que comentas por otro usuario (aunque con un fallo menor de tamaño de letra en dispositivos móviles)

Aun así te animo igualmente a hacerlo y así hay 2 propuestas diferentes. 😄

**Comment by midudev** [comment]
¡Ya tenemos mapa! :) Gracias!
