### ISSUE TITLE
Añadir gráfica de evolución de personas con pauta completa

### ISSUE THREAD

**Issue by dieortin** [midudev/covid-vacuna#52]
Al igual que se han añadido gráficas para poder ver el progreso de la distribución y vacunación, sería de gran utilidad tener una gráfica igual para las personas con pauta completa.

**Comment by devagja** [comment]
https://github.com/midudev/covid-vacuna/pull/56

**Comment by othermore** [comment]
+1. Y también ver el número de personas que llevan más de 21 días con una dosis puesta y sin la segunda, y cuántas dosis van a hacer falta en las próximas tres semanas, por semana.
