### ISSUE TITLE
Para seccion: En los medios

### ISSUE THREAD

**Issue by wedwin53** [midudev/covid-vacuna#62]
Hola, encontré que el medio "El Confidencial" puso esta nota tambien. 🚀

https://www.elconfidencial.com/tecnologia/ciencia/2021-01-24/vacunacion-web-campana-comunidad-autonoma_2918627/

**Comment by sergioedo** [comment]
Añadí nueva PR https://github.com/midudev/covid-vacuna/pull/114, faltaban los textos en los distintos idiomas

**Comment by midudev** [comment]
Gracias @sergioedo 🤗
