### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by iupac98** [midudev/covid-vacuna#66]
Hola

En primer lugar quiero agradecer y felicitaros por la creación de esta página, creo que va a ayudar a muchos a ver un horizonte y aportar esperanza en esta pandemia.

Mi sugerencia es sencilla, se trataría de crear una función que permita estimar qué porcentaje de vacunados habrá dentro de un determinado tiempo, por ejemplo, en marzo o en abril, partiendo del ritmo que se ha llevado hasta el momento. Y si además se pudiera ver la velocidad aproximada con que se está vacunando, y calcular cómo cambiaría la estimación en función del aumento en la velocidad, sería todavía mejor, aunque quizás es pedir mucho por el momento.

Muchas gracias y seguid así,

Agustín Calvo

**Comment by pangeasi** [comment]
hola, hay una funcionalidad propuesta como la que comentas, relacionada #59 aún así buena sugerencia :+1:

**Comment by iupac98** [comment]
Me alegra saberlo, gracias por contestar tan rápido!

Un saludo,

Agustín

________________________________
De: Dani Ballesteros <notifications@github.com>
Enviado: martes, 26 de enero de 2021 21:44
Para: midudev/covid-vacuna <covid-vacuna@noreply.github.com>
Cc: iupac98 <agustincalvo@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [midudev/covid-vacuna] Sugerencia (#66)


hola, hay una funcionalidad propuesta como la que comentas, relacionada #59<https://github.com/midudev/covid-vacuna/pull/59> aún así buena sugerencia 👍

**Comment by midudev** [comment]
¡Hola! Ya hemos incluido la funcionalidad que pedías. Espero que te sirva. 🤗 

![image](https://user-images.githubusercontent.com/1561955/106882891-8fb9f100-66df-11eb-8d80-9f43c384a85e.png)

**Comment by iupac98** [comment]
¡Estupendo! Magnífico trabajo, seguido así! :)
