### ISSUE TITLE
Error con safari

### ISSUE THREAD

**Issue by molivaresr** [midudev/covid-vacuna#68]
Hola! tengo un error con la visualización en Safari, estoy utilizando macOS Catalina 10.15.6 (19G2021).
![Captura de pantalla 2021-01-26 a las 23 37 24](https://user-images.githubusercontent.com/69109375/105915160-ae5d1f80-602f-11eb-89d6-3bc58b441a02.png)
No cargan colaboradores, no cargan gráficos correctamente.
Escribo por si hay algún error en mi configuración.
Saludos

PD: Visualizo en Chrome y se visualiza correctamente.

**Comment by midudev** [comment]
¡Hola! Gracias por avisar. He probado con Safari y a mi me aparece bien pero desde luego tiene pinta que algo no está funcionando correctamente.

¿Si refrescas dándole al icono de la barra de direcciones sigue pasando?

¿Sabrías abrir las herramientas de desarrollo e ir a la Consola para poder pegar aquí si ves algún error? ¡Gracias!

**Comment by molivaresr** [comment]
Hola! Pues luego de revisarlo con Chrome y Safari ambas consolas me dan un error, te copio lo de safari. 

[Error] <link rel=preload> has an invalid `imagesrcset` value (covid-vacuna.app, line 1)
[Error] <link rel=preload> has an invalid `imagesrcset` value (covid-vacuna.app, line 1)
[Error] <link rel=preload> has an invalid `imagesrcset` value (covid-vacuna.app, line 1)
[Error] <link rel=preload> has an invalid `imagesrcset` value (covid-vacuna.app, line 1)
[Error] <link rel=preload> has an invalid `imagesrcset` value (covid-vacuna.app, line 1)

``` <link rel="preload" as="image" imagesrcset="/_next/image?url=%2Fpfizer-logo.png&amp;w=96&amp;q=75 1x, /_next/image?url=%2Fpfizer-logo.png&amp;w=256&amp;q=75 2x"/>
    <link rel="preload" as="image" imagesrcset="/_next/image?url=%2Fmoderna-logo.png&amp;w=96&amp;q=75 1x, /_next/image?url=%2Fmoderna-logo.png&amp;w=256&amp;q=75 2x"/>
    <link rel="preload" as="image" imagesrcset="/_next/image?url=%2Fvacuna.png&amp;w=256&amp;q=75 1x, /_next/image?url=%2Fvacuna.png&amp;w=384&amp;q=75 2x"/>
    <link rel="preload" as="image" imagesrcset="/_next/image?url=%2Fvacunas-completas.png&amp;w=256&amp;q=75 1x, /_next/image?url=%2Fvacunas-completas.png&amp;w=384&amp;q=75 2x"/>
    <meta name="next-head-count" content="32"/> 
```

<br>
<img width="753" alt="Captura de pantalla 2021-01-27 a las 12 41 57" src="https://user-images.githubusercontent.com/69109375/105986336-16961a80-609d-11eb-954d-1d0eabcb0b94.png">

``` 
function uu(e, t) {
            try {
                **console.error(t.value)**
            } catch (n) {
                setTimeout((function() {
                    throw n
                }))
            }
        }
```
<br>
<img width="757" alt="Captura de pantalla 2021-01-27 a las 12 45 07" src="https://user-images.githubusercontent.com/69109375/105986653-7e4c6580-609d-11eb-9fa8-111e1765caa3.png">

``` 
function ve(e) {
            var t = e.App,
                n = e.err;
            **return console.error(n), Z.loadPage("/_error").then((function(r) {**
                var o = r.page,
                    a = r.styleSheets,
                    i = Se(t),
                    c = {
                        Component: o,
                        AppTree: i,
                        router: re,
                        ctx: {
                            err: n,
                            pathname: M,
                            query: I,
                            asPath: G,
                            AppTree: i
                        }
                    };
                return Promise.resolve(e.props ? e.props : (0, x.loadGetInitialProps)(t, c)).then((function(t) {
                    return be((0, v.default)({}, e, {
                        err: n,
                        Component: o,
                        styleSheets: a,
                        props: t
                    }))
                }))
            }))
        }
```

PD: No tengo experiencia, espero que sea útil la forma de reportarlo.
Saludos!

**Comment by midudev** [comment]
Ya me imagino que el problema e que falta tener un polyfill para los navegadores que no soportan Intl.RelativeTimeFormat. ¡Gracias por tu ayuda!
