### ISSUE TITLE
Bug en los números de la tabla de datos

### ISSUE THREAD

**Issue by AngelDC1412** [midudev/covid-vacuna#7]
Al ordenar las columnas está tomando los datos como si fueran decimales es decir, que en vez de interpretarlo como un numero entero, el punto de los 'miles', lo está interpreta como si fuera una 'coma'. De  ahí que haga mal la ordenación en las columnas de 'Dosis completas', 'Dosis suministradas' y 'Pautas Completas'
![BugDecimales](https://user-images.githubusercontent.com/76445853/105365450-8cface80-5bfe-11eb-8a64-e2694a959f5a.png)

**Comment by midudev** [comment]
Ya había creado una issue para esto: https://github.com/midudev/covid-vacuna/issues/3

Pero vamos a seguir aquí que tiene más info. :)

El bug es que está ordenando por los strings en lugar del valor raw. Si alguien tiene tiempo de mirarlo, el problema está en el componente Table.

**Comment by erikpr1994** [comment]
Hola!
He estado investigando y parece que el problema es que Intl.NumberFormat convierte el numero a un string. 
A la hora de ordenar, ordena hasta el primer punto y por eso aparece mal ordenado.

No he encontrado ninguna manera efectiva de ordenarlo correctamente que no sea no usando Intl, aunque seguro que @midudev acaba encontrando solución!

**Comment by pablis6** [comment]
Buenas, es un tema del locale del Intl.NumberFormat. si le pasas es-ES, no se por que, los numeros hasta el 9.999 no le pone el separados de miles, mi solución en otras ocasiones ha sido poner el locale de-DE (el de Alemania por ejemplo, pero probablemente funcione con más) y ese si que pone los puntos de miles y la ordenacion ya se haría bien tal y como lo tienes ahora.

**Comment by pablis6** [comment]
Sobre este tema también comentar que según como ordenes, la fila de totales se va arriba del todo o se cuela por medio. Probablemente sea más legible si siempre está al final de la tabla, como un pie de tabla.
¿Cómo lo veis?

**Comment by midudev** [comment]
Lo ha arreglado @pangeasi  en la PR. Voy cerrando. :)
