### ISSUE TITLE
Superposición de botones

### ISSUE THREAD

**Issue by nacholopex** [midudev/covid-vacuna#71]
![image](https://user-images.githubusercontent.com/24817636/105988648-3ed34880-60a0-11eb-9c23-af051de72a66.png)

Tras añadir los botones de idioma,, en los dispositivos móviles la parte superior empieza a estar algo satura y en algunos modelos se superponen los botones.

**Comment by midudev** [comment]
Mira a ver si el fix de javi te sirve! 👍

**Comment by nacholopex** [comment]
¡Funcionando!🎉
