### ISSUE TITLE
Problema getStaticProps y getServerSideProps a la vez

### ISSUE THREAD

**Issue by devagja** [midudev/covid-vacuna#79]
Hola a todos, 
en primer lugar la web esta quedando muy chula y encima con Nextjs! hay gente que piensa que usarlo es hacer brujería!

yendo un poco al tema, el motivo por el cual incorporé el cambio de color por localStorage es por el problema que en su día me encontré al intentar desarrollarlo, pero veo que es bastante complejo, 
  
la casuística es la siguiente:

si intentas añadir a la pagina ambas funciones os saldrá el siguiente error: 
You can not use getStaticProps or getStaticPaths with getServerSideProps. To use SSG, please remove getServerSideProps

es comprensible pero sigo sin entender el motivo de esta limitación, aunque sus razones tendrán.
 
Alguien conoce alguna forma de que ambos convivan a la vez, es necesario para poder usar las cookies y guardar el tema de la web

os dejo por aquí el hilo oficial aunque tiene algo de inactividad
https://github.com/vercel/next.js/issues/11309

también quiero preguntar, especialmente a @midudev, que os parece StaticQuery de Gatsby y cuanto estimáis que queda para que sea realidad en Nextjs.

https://github.com/vercel/next.js/discussions/13390

Muchas gracias, un saludo

**Comment by pangeasi** [comment]
Hola @devagja, no entiendo muy bien lo señalado o que quieres hacer. Yo creo que el motivo por el que no se pueden usar ambas en un misma página es porque que ambas funciones a parte de dónde ocurran están inyectando props a la página y si en un principio una página va a tener las props estáticas no podrá también hacerlas para el SSR. La limitación esta ahí presente.

**Comment by devagja** [comment]
Muchas gracias @pangeasi por la aclaración, quería implementar cookies pero es exactamente lo que has explicado 😄

**Comment by pangeasi** [comment]
@devagja  no poder settear una cookie en el servidor entiendo que no deberia ser el problema, pues puedes decidir si un componente se renderiza solo desde cliente, se me ocurre utilizando la la condicion ```typeof window !== 'undefined'```
