### ISSUE TITLE
Bug en el mapa

### ISSUE THREAD

**Issue by frmjar** [midudev/covid-vacuna#89]
Mirando un poco por encima el mapa, el popup con la información de cada comunidad aparece muy arriba de la pantalla.
Si haces demasiado scroll a la página y te pones sobre el mapa, el popup no se ve. 
Siempre sale muy alto. Debería de salir mas cerca del mapa y cambiar su posición dependiendo del scroll de la pantalla y quizás la comunidad para que aparezca arriba, abajo, izquierda y derecha.

La letra también me parece demasiado pequeña.

![image](https://user-images.githubusercontent.com/16623932/106203765-34a66c80-61bc-11eb-94c1-a1ebf843eb3f.png)

**Comment by frmjar** [comment]
> Mirando un poco por encima el mapa, el popup con la información de cada comunidad aparece muy arriba de la pantalla.
> Si haces demasiado scroll a la página y te pones sobre el mapa, el popup no se ve.
> Siempre sale muy alto. Debería de salir mas cerca del mapa y cambiar su posición dependiendo del scroll de la pantalla y quizás la comunidad para que aparezca arriba, abajo, izquierda y derecha.
> 
> La letra también me parece demasiado pequeña.
> 
> ![image](https://user-images.githubusercontent.com/16623932/106203765-34a66c80-61bc-11eb-94c1-a1ebf843eb3f.png)

Ahora no sé por qué pero no se ve el resumen.

![image](https://user-images.githubusercontent.com/16623932/106211496-362a6180-61c9-11eb-90a4-468d8ced432a.png)
![image](https://user-images.githubusercontent.com/16623932/106211506-3c204280-61c9-11eb-9391-d5aa10265979.png)

**Comment by sergioedo** [comment]
Si, a mi también me pasa, desde chrome la ubicación del popup es correcta (se ubica sobre la comunidad), pero sin datos. 

<img src="https://user-images.githubusercontent.com/5507031/106286738-43396600-6246-11eb-9b4e-d8d9de0374d1.png" width="300px" height="300px" />

¿Igual ha habido algún cambio en los datos? Solo veo este error en la consola, parece del service worker...
![image](https://user-images.githubusercontent.com/5507031/106287057-ab884780-6246-11eb-9202-eb9284f5aa5d.png)

**Comment by sergioedo** [comment]
Por lo que he podido revisar, es tema de estilos y creo que algun ajuste que se hizo para que no le afectara el dar-mode. Se fuerza un background-color a blanco aqui:

https://github.com/midudev/covid-vacuna/blob/ffd6e3193a1a41929b974920914b42ae00181d48/styles/Map.module.css#L14

Y como la fuente es blanca no se ven los datos. El borde negro imagino que vendrá por lo mismo.

**Comment by frmjar** [comment]
> Por lo que he podido revisar, es tema de estilos y creo que algun ajuste que se hizo para que no le afectara el dar-mode. Se fuerza un background-color a blanco aqui:
> 
> https://github.com/midudev/covid-vacuna/blob/ffd6e3193a1a41929b974920914b42ae00181d48/styles/Map.module.css#L14
> 
> Y como la fuente es blanca no se ven los datos. El borde negro imagino que vendrá por lo mismo.


Pude ser, pero si te fijas en mi tercera captura, el popup donde tendría que salir la infor, es muy estrecho, como si no hubiera datos que mostrar.
Puede que estén ocurriendo dos cosas a la vez, lo que tú dices del color blanco, y algún otro error a la hora de recoger/mostrar esos datos?

**Comment by frmjar** [comment]
Veo que ya está solucionado. 
Cierro el issue.
