### ISSUE TITLE
PWA instalada - No actualiza versión

### ISSUE THREAD

**Issue by sergioedo** [midudev/covid-vacuna#95]
Tras instalar la aplicación en el mòvil (funcionalida de PWA), por más que refresco (con el swipe de arriba a abajo), sigo viendo la versión de hace 6 días (donde aun no había mapa de las comunidades):

<table border="0"><tr><td>
<img src="https://user-images.githubusercontent.com/5507031/106288575-84327a00-6248-11eb-8d52-13c89e6e18c5.png" width="270" height="550" /></td><td>
<img src="https://user-images.githubusercontent.com/5507031/106288641-96141d00-6248-11eb-8719-9a64619add3b.png" width="270" height="550" /></td></tr>
</table>

Mientras que en el navegador del movil (chrome), me aparece la más reciente, incluso me propone instalarla, cuando ya la tengo (supongo que debe detectar que es otra versión)

<img src="https://user-images.githubusercontent.com/5507031/106289819-04a5aa80-624a-11eb-889a-af7ab423cee9.png" width="270" height="550" />

**Comment by Daniellop1** [comment]
Hola, prueba a desinstalar la PWA y volverla a instalar desde ek botón que sale en la última foto.

Un saludo.

**Comment by midudev** [comment]
No sé si es que te instaló una versión distinta o hicimos algún cambio que afectó, pero yo tengo la PWA instalada en Android y se me actualizó sin problemas estas semanas. No se me ocurre que podría ser.

**Comment by sergioedo** [comment]
Pues trasteando conseguí ver la URL a la que apuntaba y....tachan! Mea culpa 😞, por error instalé una versión no final (imagino que tendría alguna ventana de preview de alguna feature), y por eso no se actualizaba... 
Así que tema resuelto, perdón por las molestias.

<img src="https://user-images.githubusercontent.com/5507031/107112738-14c91580-685a-11eb-9c9b-ca4d48df0d03.png" width="270" height="550" />
